/** 
 * Autogenerated by Recite18th from table ruklis3.admin
 * Don't change this file. Instead, change the derived class AdminModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _AdminModel extends Model
{
    public String id;
    public String username;
    public String password;
    public String peran;
    public _AdminModel()
    {
        tableName="admin";
        pkFieldName="id";
        fqn = AdminModel.class.getName();
        plainClassName = "AdminModel";
    }
    public void setId(String id)
    {
        this.id=id;
    }
    public String getId()
    {        return this.id;
    }
    public void setUsername(String username)
    {
        this.username=username;
    }
    public String getUsername()
    {        return this.username;
    }
    public void setPassword(String password)
    {
        this.password=password;
    }
    public String getPassword()
    {        return this.password;
    }
    public void setPeran(String peran)
    {
        this.peran=peran;
    }
    public String getPeran()
    {        return this.peran;
    }
    public void get()
    {
        _AdminModel result = (_AdminModel) super.getModel();
        if(result!=null)
        {
            setId(result.getId());
            setUsername(result.getUsername());
            setPassword(result.getPassword());
            setPeran(result.getPeran());
        }
    }
}
