/** 
 * Autogenerated by Recite18th from table ruklis3.domain
 * Don't change this file. Instead, change the derived class DomainModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _DomainModel extends Model
{
    public String iddomain;
    public String domain;
    public _DomainModel()
    {
        tableName="domain";
        pkFieldName="iddomain";
        fqn = DomainModel.class.getName();
        plainClassName = "DomainModel";
    }
    public void setIddomain(String iddomain)
    {
        this.iddomain=iddomain;
    }
    public String getIddomain()
    {        return this.iddomain;
    }
    public void setDomain(String domain)
    {
        this.domain=domain;
    }
    public String getDomain()
    {        return this.domain;
    }
    public void get()
    {
        _DomainModel result = (_DomainModel) super.getModel();
        if(result!=null)
        {
            setIddomain(result.getIddomain());
            setDomain(result.getDomain());
        }
    }
}
