/** 
 * Autogenerated by Recite18th from table ruklis3.kelulusan_bobot
 * Don't change this file. Instead, change the derived class KelulusanBobotModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _KelulusanBobotModel extends Model
{
    public String idkelulusan_bobot;
    public String idkelulusan;
    public String idkriteria_kelulusan;
    public String bobot;
    public _KelulusanBobotModel()
    {
        tableName="kelulusan_bobot";
        pkFieldName="idkelulusan_bobot";
        fqn = KelulusanBobotModel.class.getName();
        plainClassName = "KelulusanBobotModel";
    }
    public void setIdkelulusan_bobot(String idkelulusan_bobot)
    {
        this.idkelulusan_bobot=idkelulusan_bobot;
    }
    public String getIdkelulusan_bobot()
    {        return this.idkelulusan_bobot;
    }
    public void setIdkelulusan(String idkelulusan)
    {
        this.idkelulusan=idkelulusan;
    }
    public String getIdkelulusan()
    {        return this.idkelulusan;
    }
    public void setIdkriteria_kelulusan(String idkriteria_kelulusan)
    {
        this.idkriteria_kelulusan=idkriteria_kelulusan;
    }
    public String getIdkriteria_kelulusan()
    {        return this.idkriteria_kelulusan;
    }
    public void setBobot(String bobot)
    {
        this.bobot=bobot;
    }
    public String getBobot()
    {        return this.bobot;
    }
    public void get()
    {
        _KelulusanBobotModel result = (_KelulusanBobotModel) super.getModel();
        if(result!=null)
        {
            setIdkelulusan_bobot(result.getIdkelulusan_bobot());
            setIdkelulusan(result.getIdkelulusan());
            setIdkriteria_kelulusan(result.getIdkriteria_kelulusan());
            setBobot(result.getBobot());
        }
    }
}
