/** 
 * Autogenerated by Recite18th from table ruklis3.kriteria_kelulusan
 * Don't change this file. Instead, change the derived class KriteriaKelulusanModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _KriteriaKelulusanModel extends Model
{
    public String idkriteria_kelulusan;
    public String kriteria_kelulusan;
    public _KriteriaKelulusanModel()
    {
        tableName="kriteria_kelulusan";
        pkFieldName="idkriteria_kelulusan";
        fqn = KriteriaKelulusanModel.class.getName();
        plainClassName = "KriteriaKelulusanModel";
    }
    public void setIdkriteria_kelulusan(String idkriteria_kelulusan)
    {
        this.idkriteria_kelulusan=idkriteria_kelulusan;
    }
    public String getIdkriteria_kelulusan()
    {        return this.idkriteria_kelulusan;
    }
    public void setKriteria_kelulusan(String kriteria_kelulusan)
    {
        this.kriteria_kelulusan=kriteria_kelulusan;
    }
    public String getKriteria_kelulusan()
    {        return this.kriteria_kelulusan;
    }
    public void get()
    {
        _KriteriaKelulusanModel result = (_KriteriaKelulusanModel) super.getModel();
        if(result!=null)
        {
            setIdkriteria_kelulusan(result.getIdkriteria_kelulusan());
            setKriteria_kelulusan(result.getKriteria_kelulusan());
        }
    }
}
