/** 
 * Autogenerated by Recite18th from table ruklis3.laporan_kelulusan
 * Don't change this file. Instead, change the derived class LaporanKelulusanModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _LaporanKelulusanModel extends Model
{
    public String idlaporan_kelulusan;
    public String idpeserta_test;
    public String nilai_pembobotan;
    public String nilai_kriteria;
    public _LaporanKelulusanModel()
    {
        tableName="laporan_kelulusan";
        pkFieldName="idlaporan_kelulusan";
        fqn = LaporanKelulusanModel.class.getName();
        plainClassName = "LaporanKelulusanModel";
    }
    public void setIdlaporan_kelulusan(String idlaporan_kelulusan)
    {
        this.idlaporan_kelulusan=idlaporan_kelulusan;
    }
    public String getIdlaporan_kelulusan()
    {        return this.idlaporan_kelulusan;
    }
    public void setIdpeserta_test(String idpeserta_test)
    {
        this.idpeserta_test=idpeserta_test;
    }
    public String getIdpeserta_test()
    {        return this.idpeserta_test;
    }
    public void setNilai_pembobotan(String nilai_pembobotan)
    {
        this.nilai_pembobotan=nilai_pembobotan;
    }
    public String getNilai_pembobotan()
    {        return this.nilai_pembobotan;
    }
    public void setNilai_kriteria(String nilai_kriteria)
    {
        this.nilai_kriteria=nilai_kriteria;
    }
    public String getNilai_kriteria()
    {        return this.nilai_kriteria;
    }
    public void get()
    {
        _LaporanKelulusanModel result = (_LaporanKelulusanModel) super.getModel();
        if(result!=null)
        {
            setIdlaporan_kelulusan(result.getIdlaporan_kelulusan());
            setIdpeserta_test(result.getIdpeserta_test());
            setNilai_pembobotan(result.getNilai_pembobotan());
            setNilai_kriteria(result.getNilai_kriteria());
        }
    }
}
