/** 
 * Autogenerated by Recite18th from table ruklis3.paket_soal_jawaban
 * Don't change this file. Instead, change the derived class PaketSoalJawabanModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _PaketSoalJawabanModel extends Model
{
    public String idpaket_soal_jawaban;
    public String idpaket_soal;
    public String idsoal;
    public String idpeserta_test;
    public String jawaban;
    public _PaketSoalJawabanModel()
    {
        tableName="paket_soal_jawaban";
        pkFieldName="idpaket_soal_jawaban";
        fqn = PaketSoalJawabanModel.class.getName();
        plainClassName = "PaketSoalJawabanModel";
    }
    public void setIdpaket_soal_jawaban(String idpaket_soal_jawaban)
    {
        this.idpaket_soal_jawaban=idpaket_soal_jawaban;
    }
    public String getIdpaket_soal_jawaban()
    {        return this.idpaket_soal_jawaban;
    }
    public void setIdpaket_soal(String idpaket_soal)
    {
        this.idpaket_soal=idpaket_soal;
    }
    public String getIdpaket_soal()
    {        return this.idpaket_soal;
    }
    public void setIdsoal(String idsoal)
    {
        this.idsoal=idsoal;
    }
    public String getIdsoal()
    {        return this.idsoal;
    }
    public void setIdpeserta_test(String idpeserta_test)
    {
        this.idpeserta_test=idpeserta_test;
    }
    public String getIdpeserta_test()
    {        return this.idpeserta_test;
    }
    public void setJawaban(String jawaban)
    {
        this.jawaban=jawaban;
    }
    public String getJawaban()
    {        return this.jawaban;
    }
    public void get()
    {
        _PaketSoalJawabanModel result = (_PaketSoalJawabanModel) super.getModel();
        if(result!=null)
        {
            setIdpaket_soal_jawaban(result.getIdpaket_soal_jawaban());
            setIdpaket_soal(result.getIdpaket_soal());
            setIdsoal(result.getIdsoal());
            setIdpeserta_test(result.getIdpeserta_test());
            setJawaban(result.getJawaban());
        }
    }
}
