/** 
 * Autogenerated by Recite18th from table ruklis3.paket_soal_detail
 * Don't change this file. Instead, change the derived class PaketSoalDetailModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _PaketSoalDetailModel extends Model
{
    public String idpaket_soal_detail;
    public String idpaket_soal;
    public String idsoal;
    public String bobot;
    public _PaketSoalDetailModel()
    {
        tableName="paket_soal_detail";
        pkFieldName="idpaket_soal_detail";
        fqn = PaketSoalDetailModel.class.getName();
        plainClassName = "PaketSoalDetailModel";
    }
    public void setIdpaket_soal_detail(String idpaket_soal_detail)
    {
        this.idpaket_soal_detail=idpaket_soal_detail;
    }
    public String getIdpaket_soal_detail()
    {        return this.idpaket_soal_detail;
    }
    public void setIdpaket_soal(String idpaket_soal)
    {
        this.idpaket_soal=idpaket_soal;
    }
    public String getIdpaket_soal()
    {        return this.idpaket_soal;
    }
    public void setIdsoal(String idsoal)
    {
        this.idsoal=idsoal;
    }
    public String getIdsoal()
    {        return this.idsoal;
    }
    public void setBobot(String bobot)
    {
        this.bobot=bobot;
    }
    public String getBobot()
    {        return this.bobot;
    }
    public void get()
    {
        _PaketSoalDetailModel result = (_PaketSoalDetailModel) super.getModel();
        if(result!=null)
        {
            setIdpaket_soal_detail(result.getIdpaket_soal_detail());
            setIdpaket_soal(result.getIdpaket_soal());
            setIdsoal(result.getIdsoal());
            setBobot(result.getBobot());
        }
    }
}
