/** 
 * Autogenerated by Recite18th from table ruklis3.paket_soal_tiga_butir
 * Don't change this file. Instead, change the derived class PaketSoalTigaButirModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _PaketSoalTigaButirModel extends Model
{
    public String idpaket_soal_tiga_butir;
    public String tanggal;
    public String keterangan;
    public String waktu_maksimal;
    public _PaketSoalTigaButirModel()
    {
        tableName="paket_soal_tiga_butir";
        pkFieldName="idpaket_soal_tiga_butir";
        fqn = PaketSoalTigaButirModel.class.getName();
        plainClassName = "PaketSoalTigaButirModel";
    }
    public void setIdpaket_soal_tiga_butir(String idpaket_soal_tiga_butir)
    {
        this.idpaket_soal_tiga_butir=idpaket_soal_tiga_butir;
    }
    public String getIdpaket_soal_tiga_butir()
    {        return this.idpaket_soal_tiga_butir;
    }
    public void setTanggal(String tanggal)
    {
        this.tanggal=tanggal;
    }
    public String getTanggal()
    {        return this.tanggal;
    }
    public void setKeterangan(String keterangan)
    {
        this.keterangan=keterangan;
    }
    public String getKeterangan()
    {        return this.keterangan;
    }
    public void setWaktu_maksimal(String waktu_maksimal)
    {
        this.waktu_maksimal=waktu_maksimal;
    }
    public String getWaktu_maksimal()
    {        return this.waktu_maksimal;
    }
    public void get()
    {
        _PaketSoalTigaButirModel result = (_PaketSoalTigaButirModel) super.getModel();
        if(result!=null)
        {
            setIdpaket_soal_tiga_butir(result.getIdpaket_soal_tiga_butir());
            setTanggal(result.getTanggal());
            setKeterangan(result.getKeterangan());
            setWaktu_maksimal(result.getWaktu_maksimal());
        }
    }
}
