/** 
 * Autogenerated by Recite18th from table ruklis3.paket_soal_tiga_butir_detail
 * Don't change this file. Instead, change the derived class PaketSoalTigaButirDetailModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _PaketSoalTigaButirDetailModel extends Model
{
    public String idpaket_soal_tiga_butir_detail;
    public String idpaket_soal_tiga_butir;
    public String idsoal;
    public _PaketSoalTigaButirDetailModel()
    {
        tableName="paket_soal_tiga_butir_detail";
        pkFieldName="idpaket_soal_tiga_butir_detail";
        fqn = PaketSoalTigaButirDetailModel.class.getName();
        plainClassName = "PaketSoalTigaButirDetailModel";
    }
    public void setIdpaket_soal_tiga_butir_detail(String idpaket_soal_tiga_butir_detail)
    {
        this.idpaket_soal_tiga_butir_detail=idpaket_soal_tiga_butir_detail;
    }
    public String getIdpaket_soal_tiga_butir_detail()
    {        return this.idpaket_soal_tiga_butir_detail;
    }
    public void setIdpaket_soal_tiga_butir(String idpaket_soal_tiga_butir)
    {
        this.idpaket_soal_tiga_butir=idpaket_soal_tiga_butir;
    }
    public String getIdpaket_soal_tiga_butir()
    {        return this.idpaket_soal_tiga_butir;
    }
    public void setIdsoal(String idsoal)
    {
        this.idsoal=idsoal;
    }
    public String getIdsoal()
    {        return this.idsoal;
    }
    public void get()
    {
        _PaketSoalTigaButirDetailModel result = (_PaketSoalTigaButirDetailModel) super.getModel();
        if(result!=null)
        {
            setIdpaket_soal_tiga_butir_detail(result.getIdpaket_soal_tiga_butir_detail());
            setIdpaket_soal_tiga_butir(result.getIdpaket_soal_tiga_butir());
            setIdsoal(result.getIdsoal());
        }
    }
}
