/** 
 * Autogenerated by Recite18th from table ruklis3.paket_soal_tiga_butir_jawaban
 * Don't change this file. Instead, change the derived class PaketSoalTigaButirJawabanModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _PaketSoalTigaButirJawabanModel extends Model
{
    public String idpaket_soal_tiga_butir_jawaban;
    public String idpaket_soal_tiga_butir;
    public String idsoal;
    public String idpeserta_test;
    public String jawaban;
    public _PaketSoalTigaButirJawabanModel()
    {
        tableName="paket_soal_tiga_butir_jawaban";
        pkFieldName="idpaket_soal_tiga_butir_jawaban";
        fqn = PaketSoalTigaButirJawabanModel.class.getName();
        plainClassName = "PaketSoalTigaButirJawabanModel";
    }
    public void setIdpaket_soal_tiga_butir_jawaban(String idpaket_soal_tiga_butir_jawaban)
    {
        this.idpaket_soal_tiga_butir_jawaban=idpaket_soal_tiga_butir_jawaban;
    }
    public String getIdpaket_soal_tiga_butir_jawaban()
    {        return this.idpaket_soal_tiga_butir_jawaban;
    }
    public void setIdpaket_soal_tiga_butir(String idpaket_soal_tiga_butir)
    {
        this.idpaket_soal_tiga_butir=idpaket_soal_tiga_butir;
    }
    public String getIdpaket_soal_tiga_butir()
    {        return this.idpaket_soal_tiga_butir;
    }
    public void setIdsoal(String idsoal)
    {
        this.idsoal=idsoal;
    }
    public String getIdsoal()
    {        return this.idsoal;
    }
    public void setIdpeserta_test(String idpeserta_test)
    {
        this.idpeserta_test=idpeserta_test;
    }
    public String getIdpeserta_test()
    {        return this.idpeserta_test;
    }
    public void setJawaban(String jawaban)
    {
        this.jawaban=jawaban;
    }
    public String getJawaban()
    {        return this.jawaban;
    }
    public void get()
    {
        _PaketSoalTigaButirJawabanModel result = (_PaketSoalTigaButirJawabanModel) super.getModel();
        if(result!=null)
        {
            setIdpaket_soal_tiga_butir_jawaban(result.getIdpaket_soal_tiga_butir_jawaban());
            setIdpaket_soal_tiga_butir(result.getIdpaket_soal_tiga_butir());
            setIdsoal(result.getIdsoal());
            setIdpeserta_test(result.getIdpeserta_test());
            setJawaban(result.getJawaban());
        }
    }
}
