/** 
 * Autogenerated by Recite18th from table ruklis3.paket_soal
 * Don't change this file. Instead, change the derived class PaketSoalModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _PaketSoalModel extends Model
{
    public String idpaket_soal;
    public String tanggal;
    public String keterangan;
    public String waktu_maksimal;
    public _PaketSoalModel()
    {
        tableName="paket_soal";
        pkFieldName="idpaket_soal";
        fqn = PaketSoalModel.class.getName();
        plainClassName = "PaketSoalModel";
    }
    public void setIdpaket_soal(String idpaket_soal)
    {
        this.idpaket_soal=idpaket_soal;
    }
    public String getIdpaket_soal()
    {        return this.idpaket_soal;
    }
    public void setTanggal(String tanggal)
    {
        this.tanggal=tanggal;
    }
    public String getTanggal()
    {        return this.tanggal;
    }
    public void setKeterangan(String keterangan)
    {
        this.keterangan=keterangan;
    }
    public String getKeterangan()
    {        return this.keterangan;
    }
    public void setWaktu_maksimal(String waktu_maksimal)
    {
        this.waktu_maksimal=waktu_maksimal;
    }
    public String getWaktu_maksimal()
    {        return this.waktu_maksimal;
    }
    public void get()
    {
        _PaketSoalModel result = (_PaketSoalModel) super.getModel();
        if(result!=null)
        {
            setIdpaket_soal(result.getIdpaket_soal());
            setTanggal(result.getTanggal());
            setKeterangan(result.getKeterangan());
            setWaktu_maksimal(result.getWaktu_maksimal());
        }
    }
}
