/** 
 * Autogenerated by Recite18th from table ruklis3.pembobotan
 * Don't change this file. Instead, change the derived class PembobotanModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _PembobotanModel extends Model
{
    public String idpembobotan;
    public String nama_pembobotan;
    public _PembobotanModel()
    {
        tableName="pembobotan";
        pkFieldName="idpembobotan";
        fqn = PembobotanModel.class.getName();
        plainClassName = "PembobotanModel";
    }
    public void setIdpembobotan(String idpembobotan)
    {
        this.idpembobotan=idpembobotan;
    }
    public String getIdpembobotan()
    {        return this.idpembobotan;
    }
    public void setNama_pembobotan(String nama_pembobotan)
    {
        this.nama_pembobotan=nama_pembobotan;
    }
    public String getNama_pembobotan()
    {        return this.nama_pembobotan;
    }
    public void get()
    {
        _PembobotanModel result = (_PembobotanModel) super.getModel();
        if(result!=null)
        {
            setIdpembobotan(result.getIdpembobotan());
            setNama_pembobotan(result.getNama_pembobotan());
        }
    }
}
