/** 
 * Autogenerated by Recite18th from table ruklis3.pembobotan_domain
 * Don't change this file. Instead, change the derived class PembobotanDomainModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _PembobotanDomainModel extends Model
{
    public String idpembobotan_domain;
    public String idpembobotan;
    public String iddomain;
    public String bobot;
    public _PembobotanDomainModel()
    {
        tableName="pembobotan_domain";
        pkFieldName="idpembobotan_domain";
        fqn = PembobotanDomainModel.class.getName();
        plainClassName = "PembobotanDomainModel";
    }
    public void setIdpembobotan_domain(String idpembobotan_domain)
    {
        this.idpembobotan_domain=idpembobotan_domain;
    }
    public String getIdpembobotan_domain()
    {        return this.idpembobotan_domain;
    }
    public void setIdpembobotan(String idpembobotan)
    {
        this.idpembobotan=idpembobotan;
    }
    public String getIdpembobotan()
    {        return this.idpembobotan;
    }
    public void setIddomain(String iddomain)
    {
        this.iddomain=iddomain;
    }
    public String getIddomain()
    {        return this.iddomain;
    }
    public void setBobot(String bobot)
    {
        this.bobot=bobot;
    }
    public String getBobot()
    {        return this.bobot;
    }
    public void get()
    {
        _PembobotanDomainModel result = (_PembobotanDomainModel) super.getModel();
        if(result!=null)
        {
            setIdpembobotan_domain(result.getIdpembobotan_domain());
            setIdpembobotan(result.getIdpembobotan());
            setIddomain(result.getIddomain());
            setBobot(result.getBobot());
        }
    }
}
