/** 
 * Autogenerated by Recite18th from table ruklis3.peserta_test_kriteria_kelulusan
 * Don't change this file. Instead, change the derived class PesertaTestKriteriaKelulusanModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _PesertaTestKriteriaKelulusanModel extends Model
{
    public String idpeserta_test_kriteria_kelulusan;
    public String idpeserta_test;
    public String idkriteria_kelulusan;
    public String nilai;
    public _PesertaTestKriteriaKelulusanModel()
    {
        tableName="peserta_test_kriteria_kelulusan";
        pkFieldName="idpeserta_test_kriteria_kelulusan";
        fqn = PesertaTestKriteriaKelulusanModel.class.getName();
        plainClassName = "PesertaTestKriteriaKelulusanModel";
    }
    public void setIdpeserta_test_kriteria_kelulusan(String idpeserta_test_kriteria_kelulusan)
    {
        this.idpeserta_test_kriteria_kelulusan=idpeserta_test_kriteria_kelulusan;
    }
    public String getIdpeserta_test_kriteria_kelulusan()
    {        return this.idpeserta_test_kriteria_kelulusan;
    }
    public void setIdpeserta_test(String idpeserta_test)
    {
        this.idpeserta_test=idpeserta_test;
    }
    public String getIdpeserta_test()
    {        return this.idpeserta_test;
    }
    public void setIdkriteria_kelulusan(String idkriteria_kelulusan)
    {
        this.idkriteria_kelulusan=idkriteria_kelulusan;
    }
    public String getIdkriteria_kelulusan()
    {        return this.idkriteria_kelulusan;
    }
    public void setNilai(String nilai)
    {
        this.nilai=nilai;
    }
    public String getNilai()
    {        return this.nilai;
    }
    public void get()
    {
        _PesertaTestKriteriaKelulusanModel result = (_PesertaTestKriteriaKelulusanModel) super.getModel();
        if(result!=null)
        {
            setIdpeserta_test_kriteria_kelulusan(result.getIdpeserta_test_kriteria_kelulusan());
            setIdpeserta_test(result.getIdpeserta_test());
            setIdkriteria_kelulusan(result.getIdkriteria_kelulusan());
            setNilai(result.getNilai());
        }
    }
}
