/** 
 * Autogenerated by Recite18th from table ruklis3.peserta_test
 * Don't change this file. Instead, change the derived class PesertaTestModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _PesertaTestModel extends Model
{
    public String id;
    public String username;
    public String password;
    public String peran;
    public String nomor_peserta;
    public String metode;
    public String model_logistik;
    public String penyajian_soal;
    public String inisialisasi_kemampuan;
    public String nama_lengkap;
    public String asal;
    public String tempat_lahir;
    public String tanggal_lahir;
    public String jenis_kelamin;
    public String foto;
    public String idpaket_soal;
    public String skor_akhir;
    public String idpaket_soal_tiga_butir;
    public String tingkat_kesukaran;
    public _PesertaTestModel()
    {
        tableName="peserta_test";
        pkFieldName="id";
        fqn = PesertaTestModel.class.getName();
        plainClassName = "PesertaTestModel";
    }
    public void setId(String id)
    {
        this.id=id;
    }
    public String getId()
    {        return this.id;
    }
    public void setUsername(String username)
    {
        this.username=username;
    }
    public String getUsername()
    {        return this.username;
    }
    public void setPassword(String password)
    {
        this.password=password;
    }
    public String getPassword()
    {        return this.password;
    }
    public void setPeran(String peran)
    {
        this.peran=peran;
    }
    public String getPeran()
    {        return this.peran;
    }
    public void setNomor_peserta(String nomor_peserta)
    {
        this.nomor_peserta=nomor_peserta;
    }
    public String getNomor_peserta()
    {        return this.nomor_peserta;
    }
    public void setMetode(String metode)
    {
        this.metode=metode;
    }
    public String getMetode()
    {        return this.metode;
    }
    public void setModel_logistik(String model_logistik)
    {
        this.model_logistik=model_logistik;
    }
    public String getModel_logistik()
    {        return this.model_logistik;
    }
    public void setPenyajian_soal(String penyajian_soal)
    {
        this.penyajian_soal=penyajian_soal;
    }
    public String getPenyajian_soal()
    {        return this.penyajian_soal;
    }
    public void setInisialisasi_kemampuan(String inisialisasi_kemampuan)
    {
        this.inisialisasi_kemampuan=inisialisasi_kemampuan;
    }
    public String getInisialisasi_kemampuan()
    {        return this.inisialisasi_kemampuan;
    }
    public void setNama_lengkap(String nama_lengkap)
    {
        this.nama_lengkap=nama_lengkap;
    }
    public String getNama_lengkap()
    {        return this.nama_lengkap;
    }
    public void setAsal(String asal)
    {
        this.asal=asal;
    }
    public String getAsal()
    {        return this.asal;
    }
    public void setTempat_lahir(String tempat_lahir)
    {
        this.tempat_lahir=tempat_lahir;
    }
    public String getTempat_lahir()
    {        return this.tempat_lahir;
    }
    public void setTanggal_lahir(String tanggal_lahir)
    {
        this.tanggal_lahir=tanggal_lahir;
    }
    public String getTanggal_lahir()
    {        return this.tanggal_lahir;
    }
    public void setJenis_kelamin(String jenis_kelamin)
    {
        this.jenis_kelamin=jenis_kelamin;
    }
    public String getJenis_kelamin()
    {        return this.jenis_kelamin;
    }
    public void setFoto(String foto)
    {
        this.foto=foto;
    }
    public String getFoto()
    {        return this.foto;
    }
    public void setIdpaket_soal(String idpaket_soal)
    {
        this.idpaket_soal=idpaket_soal;
    }
    public String getIdpaket_soal()
    {        return this.idpaket_soal;
    }
    public void setSkor_akhir(String skor_akhir)
    {
        this.skor_akhir=skor_akhir;
    }
    public String getSkor_akhir()
    {        return this.skor_akhir;
    }
    public void setIdpaket_soal_tiga_butir(String idpaket_soal_tiga_butir)
    {
        this.idpaket_soal_tiga_butir=idpaket_soal_tiga_butir;
    }
    public String getIdpaket_soal_tiga_butir()
    {        return this.idpaket_soal_tiga_butir;
    }
    public void setTingkat_kesukaran(String tingkat_kesukaran)
    {
        this.tingkat_kesukaran=tingkat_kesukaran;
    }
    public String getTingkat_kesukaran()
    {        return this.tingkat_kesukaran;
    }
    public void get()
    {
        _PesertaTestModel result = (_PesertaTestModel) super.getModel();
        if(result!=null)
        {
            setId(result.getId());
            setUsername(result.getUsername());
            setPassword(result.getPassword());
            setPeran(result.getPeran());
            setNomor_peserta(result.getNomor_peserta());
            setMetode(result.getMetode());
            setModel_logistik(result.getModel_logistik());
            setPenyajian_soal(result.getPenyajian_soal());
            setInisialisasi_kemampuan(result.getInisialisasi_kemampuan());
            setNama_lengkap(result.getNama_lengkap());
            setAsal(result.getAsal());
            setTempat_lahir(result.getTempat_lahir());
            setTanggal_lahir(result.getTanggal_lahir());
            setJenis_kelamin(result.getJenis_kelamin());
            setFoto(result.getFoto());
            setIdpaket_soal(result.getIdpaket_soal());
            setSkor_akhir(result.getSkor_akhir());
            setIdpaket_soal_tiga_butir(result.getIdpaket_soal_tiga_butir());
            setTingkat_kesukaran(result.getTingkat_kesukaran());
        }
    }
}
