/** 
 * Autogenerated by Recite18th from table ruklis3.peserta_test_domain
 * Don't change this file. Instead, change the derived class PesertaTestDomainModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _PesertaTestDomainModel extends Model
{
    public String idpeserta_test_domain;
    public String idpeserta_test;
    public String iddomain;
    public _PesertaTestDomainModel()
    {
        tableName="peserta_test_domain";
        pkFieldName="idpeserta_test_domain";
        fqn = PesertaTestDomainModel.class.getName();
        plainClassName = "PesertaTestDomainModel";
    }
    public void setIdpeserta_test_domain(String idpeserta_test_domain)
    {
        this.idpeserta_test_domain=idpeserta_test_domain;
    }
    public String getIdpeserta_test_domain()
    {        return this.idpeserta_test_domain;
    }
    public void setIdpeserta_test(String idpeserta_test)
    {
        this.idpeserta_test=idpeserta_test;
    }
    public String getIdpeserta_test()
    {        return this.idpeserta_test;
    }
    public void setIddomain(String iddomain)
    {
        this.iddomain=iddomain;
    }
    public String getIddomain()
    {        return this.iddomain;
    }
    public void get()
    {
        _PesertaTestDomainModel result = (_PesertaTestDomainModel) super.getModel();
        if(result!=null)
        {
            setIdpeserta_test_domain(result.getIdpeserta_test_domain());
            setIdpeserta_test(result.getIdpeserta_test());
            setIddomain(result.getIddomain());
        }
    }
}
