/** 
 * Autogenerated by Recite18th from table ruklis3.soal
 * Don't change this file. Instead, change the derived class SoalModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _SoalModel extends Model
{
    public String idsoal;
    public String iddomain;
    public String soal;
    public String gambar;
    public String jawaban;
    public String lg1_b;
    public String lg2_a;
    public String lg2_b;
    public String lg3_a;
    public String lg3_b;
    public String lg3_c;
    public String rasch_b;
    public String idskl;
    public _SoalModel()
    {
        tableName="soal";
        pkFieldName="idsoal";
        fqn = SoalModel.class.getName();
        plainClassName = "SoalModel";
    }
    public void setIdsoal(String idsoal)
    {
        this.idsoal=idsoal;
    }
    public String getIdsoal()
    {        return this.idsoal;
    }
    public void setIddomain(String iddomain)
    {
        this.iddomain=iddomain;
    }
    public String getIddomain()
    {        return this.iddomain;
    }
    public void setSoal(String soal)
    {
        this.soal=soal;
    }
    public String getSoal()
    {        return this.soal;
    }
    public void setGambar(String gambar)
    {
        this.gambar=gambar;
    }
    public String getGambar()
    {        return this.gambar;
    }
    public void setJawaban(String jawaban)
    {
        this.jawaban=jawaban;
    }
    public String getJawaban()
    {        return this.jawaban;
    }
    public void setLg1_b(String lg1_b)
    {
        this.lg1_b=lg1_b;
    }
    public String getLg1_b()
    {        return this.lg1_b;
    }
    public void setLg2_a(String lg2_a)
    {
        this.lg2_a=lg2_a;
    }
    public String getLg2_a()
    {        return this.lg2_a;
    }
    public void setLg2_b(String lg2_b)
    {
        this.lg2_b=lg2_b;
    }
    public String getLg2_b()
    {        return this.lg2_b;
    }
    public void setLg3_a(String lg3_a)
    {
        this.lg3_a=lg3_a;
    }
    public String getLg3_a()
    {        return this.lg3_a;
    }
    public void setLg3_b(String lg3_b)
    {
        this.lg3_b=lg3_b;
    }
    public String getLg3_b()
    {        return this.lg3_b;
    }
    public void setLg3_c(String lg3_c)
    {
        this.lg3_c=lg3_c;
    }
    public String getLg3_c()
    {        return this.lg3_c;
    }
    public void setRasch_b(String rasch_b)
    {
        this.rasch_b=rasch_b;
    }
    public String getRasch_b()
    {        return this.rasch_b;
    }
    public void setIdskl(String idskl)
    {
        this.idskl=idskl;
    }
    public String getIdskl()
    {        return this.idskl;
    }
    public void get()
    {
        _SoalModel result = (_SoalModel) super.getModel();
        if(result!=null)
        {
            setIdsoal(result.getIdsoal());
            setIddomain(result.getIddomain());
            setSoal(result.getSoal());
            setGambar(result.getGambar());
            setJawaban(result.getJawaban());
            setLg1_b(result.getLg1_b());
            setLg2_a(result.getLg2_a());
            setLg2_b(result.getLg2_b());
            setLg3_a(result.getLg3_a());
            setLg3_b(result.getLg3_b());
            setLg3_c(result.getLg3_c());
            setRasch_b(result.getRasch_b());
            setIdskl(result.getIdskl());
        }
    }
}
