/** 
 * Autogenerated by Recite18th from table ruklis3.wali_peserta_test
 * Don't change this file. Instead, change the derived class WaliPesertaTestModel
 * 
 */

package application.models;
import recite18th.model.Model;
public class _WaliPesertaTestModel extends Model
{
    public String id;
    public String username;
    public String password;
    public String peran;
    public String idpeserta_test;
    public _WaliPesertaTestModel()
    {
        tableName="wali_peserta_test";
        pkFieldName="id";
        fqn = WaliPesertaTestModel.class.getName();
        plainClassName = "WaliPesertaTestModel";
    }
    public void setId(String id)
    {
        this.id=id;
    }
    public String getId()
    {        return this.id;
    }
    public void setUsername(String username)
    {
        this.username=username;
    }
    public String getUsername()
    {        return this.username;
    }
    public void setPassword(String password)
    {
        this.password=password;
    }
    public String getPassword()
    {        return this.password;
    }
    public void setPeran(String peran)
    {
        this.peran=peran;
    }
    public String getPeran()
    {        return this.peran;
    }
    public void setIdpeserta_test(String idpeserta_test)
    {
        this.idpeserta_test=idpeserta_test;
    }
    public String getIdpeserta_test()
    {        return this.idpeserta_test;
    }
    public void get()
    {
        _WaliPesertaTestModel result = (_WaliPesertaTestModel) super.getModel();
        if(result!=null)
        {
            setId(result.getId());
            setUsername(result.getUsername());
            setPassword(result.getPassword());
            setPeran(result.getPeran());
            setIdpeserta_test(result.getIdpeserta_test());
        }
    }
}
