/** 
 * Autogenerated by Recite18th at Sat Nov 26 21:14:19 ICT 2011
 * 
 */

package application.models;
import recite18th.model.Model;
import application.models._KelulusanModel;
public class KelulusanModel extends _KelulusanModel
{
    public KelulusanModel()
    {
        super();
    }
}
