/** 
 * Autogenerated by Recite18th at Mon May 09 08:21:53 ICT 2011
 * 
 */

package application.models;
import recite18th.model.Model;
import application.models._PesertaTestJawabanDenganModelModel;
public class PesertaTestJawabanDenganModelModel extends _PesertaTestJawabanDenganModelModel
{
    public PesertaTestJawabanDenganModelModel()
    {
        super();
    }
}
