/** 
 * Autogenerated by Recite18th at Mon May 16 00:01:35 ICT 2011
 * 
 */

package application.models;
import recite18th.model.Model;
import application.models._PesertaTestDomainModel;
public class PesertaTestDomainModel extends _PesertaTestDomainModel
{
    public PesertaTestDomainModel()
    {
        super();
    }
}
