/** 
 * Autogenerated by Recite18th at Mon May 16 00:01:35 ICT 2011
 * 
 */

package application.models;
import application.models._SklModel;
public class SklModel extends _SklModel
{
    private String domain;

    public String getDomain() {
        return domain;
    }

    public void setDomain(String domain) {
        this.domain = domain;
    }
    public SklModel()
    {
        super();
    }
}
