<input name="idpaket_soal_jawaban" type="text" id="idpaket_soal_jawaban" value="${model.idpaket_soal_jawaban}">")
<input name="idpaket_soal" type="text" id="idpaket_soal" value="${model.idpaket_soal}">")
<input name="idsoal" type="text" id="idsoal" value="${model.idsoal}">")
<input name="idpeserta_test" type="text" id="idpeserta_test" value="${model.idpeserta_test}">")
<input name="jawaban" type="text" id="jawaban" value="${model.jawaban}">")
