<input name="id" type="text" id="id" value="${model.id}">")
<input name="username" type="text" id="username" value="${model.username}">")
<input name="password" type="text" id="password" value="${model.password}">")
<input name="peran" type="text" id="peran" value="${model.peran}">")
<input name="idpeserta_test" type="text" id="idpeserta_test" value="${model.idpeserta_test}">")
